name: Scheduled Job

on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 1 UTC every day (8 MDT)
  workflow_dispatch: {} # Allows manual triggering
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Install ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/linux64/chrome-linux64.zip
        unzip chromedriver-linux64.zip -d chromedriver-linux64
        sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver


    - name: Set up environment variables
      run: |
        echo "gmail_app_pwd=${{ secrets.GMAIL_APP_PWD }}" >> $GITHUB_ENV
        echo "distro_list=${{ secrets.DISTRO_LIST }}" >> $GITHUB_ENV
        echo "sender_email=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV

    - name: Run Python script
      run: python main.py 
      env:
          gmail_app_pwd: ${{ secrets.GMAIL_APP_PWD }}
          distro_list: ${{ secrets.DISTRO_LIST }}
          sender_email: ${{ secrets.SENDER_EMAIL }}
