name: Scheduled Job

on:
  schedule:
    - cron: '05 6 * * *' #'0 2 * * *'  # Runs at 2 am UTC every day (8 MDT)
  workflow_dispatch: {} # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Install Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Download and set up ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        echo "Chrome version: $CHROME_VERSION"
        MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)
        echo "Major Chrome version: $MAJOR_VERSION"
        
        # Fetch the known good versions JSON
        curl -s https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json -o known-good-versions.json
        
        # Parse the JSON to get the download URL for the correct ChromeDriver version
        CHROMEDRIVER_URL=$(jq -r --arg MAJOR_VERSION "$MAJOR_VERSION" '
          .versions[] |
          select(.version | startswith($MAJOR_VERSION + ".")) |
          .downloads.chromedriver[] |
          select(.platform == "linux64") |
          .url
        ' known-good-versions.json)
        
        echo "ChromeDriver URL: $CHROMEDRIVER_URL"
        
        wget -q -O /tmp/chromedriver.zip $CHROMEDRIVER_URL
        unzip /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set up environment variables
      run: |
        echo "gmail_app_pwd=${{ secrets.GMAIL_APP_PWD }}" >> $GITHUB_ENV

    - name: Run Python script
      run: python main.py 
      env:
          gmail_app_pwd: ${{ secrets.GMAIL_APP_PWD }}
