name: Scheduled Job

on:
  schedule:
    - cron: '05 6 * * *' #'0 2 * * *'  # Runs at 2 am UTC every day (8 MDT)
  workflow_dispatch: {} # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
        wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION -O /tmp/chromedriver_version
        wget https://chromedriver.storage.googleapis.com/$(cat /tmp/chromedriver_version)/chromedriver_linux64.zip -P /tmp
        unzip /tmp/chromedriver_linux64.zip -d /tmp
        sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set up environment variables
      run: |
        echo "gmail_app_pwd=${{ secrets.GMAIL_APP_PWD }}" >> $GITHUB_ENV

    - name: Run Python script
      run: python main.py 
      env:
          gmail_app_pwd: ${{ secrets.GMAIL_APP_PWD }}
