name: Scheduled Job

on:
  schedule:
    - cron: '05 6 * * *' #'0 2 * * *'  # Runs at 2 am UTC every day (8 MDT)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Set up environment variables
      run: |
        echo "gmail_app_pwd=${{ secrets.GMAIL_APP_PWD }}" >> $GITHUB_ENV

    - name: Run Python script
      run: python main.py 
      env:
          gmail_app_pwd: ${{ secrets.GMAIL_APP_PWD }}
