name: Scheduled Job

on:
  schedule:
    - cron: '49 5 * * *' #'0 2 * * *'  # Runs at 2 am UTC every day (8 MDT)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Python script
      run: python main.py  # Replace with the actual path to your script
